CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PACKAGE_ID NUMBER(10),
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST NUMBER(10, 2),
    SALE_PRICE NUMBER(10, 2),
    LAST_UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30),
    PET_FLAG VARCHAR2(1)
);

CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID NUMBER,
    LOG_DATETIME DATE,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,
    CONSTRAINT PK_PET_CARE_LOG PRIMARY KEY (PRODUCT_ID, LOG_DATETIME)
);

CREATE OR REPLACE TRIGGER log_trigger
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :NEW.LOG_DATETIME IS NULL THEN
        :NEW.LOG_DATETIME := SYSDATE;
    END IF;

    :NEW.CREATED_BY_USER := USER;
    
    EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'ERROR IN log_trigger' || SQLERRM
        );
END;

CREATE OR REPLACE TRIGGER log_trigger_update
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :OLD.CREATED_BY_USER <> USER THEN
    RAISE_APPLICATION_ERROR(
            -20001,
            'Update not allowed: user does not match the creator of the record.'
        );
    END IF;

    EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'ERROR IN log_trigger_update' || SQLERRM
        );
END;

CREATE OR REPLACE TRIGGER log_trigger_delete
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER <> 'JOEMANAGER' THEN
    RAISE_APPLICATION_ERROR(
        -20003,
        'ERROR IN log_trigger_delete, user not JOEMANAGER' || SQLERRM
        );
    END IF;

    EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'ERROR IN log_trigger_delete' || SQLERRM
        );
END;